core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]



from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

website/urls.py
from django.urls import path, re_path


from .views import (
    breakdown_view,
    about_view,
    productions_view,
    contact_view,
    view_file,
    limites,
    auth_receiver,
    sign_out,
    erreur,
    FormSuccessView,
    DocumentSuccessView,
)

app_name = "website"

urlpatterns = [
    path("about/", about_view, name="about"),
    path("productions/", productions_view, name="productions"),
    path("", breakdown_view, name="breakdown"),
    path("contact/", contact_view, name="contact"),
    path('limites/', limites, name='limites'),
    re_path(r'media/documents/[0-9]{4}/[0-9]{2}/[0-9]{2}/.+', view_file, name="view-file"),
    path('sign-out/', sign_out, name='sign_out'),
    path('auth-receiver/', auth_receiver, name='auth_receiver'),
    path('erreur/', erreur, name='erreur'),
    path("form-sent/", FormSuccessView.as_view(), name="form-sent"),
    path('document-sent/', DocumentSuccessView.as_view(), name='document-success'),
]

website/models.py
import io
from django.db import models
from django.core.validators import FileExtensionValidator
from website import handle_pdf
from django.dispatch import receiver
import os
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
import boto3
from core.settings import MEDIAFILES_LOCATION

class Message(models.Model):
    Nom = models.CharField(max_length=254)
    Email = models.EmailField()
    Objet = models.CharField(max_length=254)
    Message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

class Screenplay(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d',  validators=[FileExtensionValidator(['pdf'])])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created = models.DateTimeField(auto_now_add=True)
    titre = models.CharField(max_length=254, default="")
    authors = models.CharField(max_length=254, default="")
    

class Breakdown(models.Model):
    screenplay = models.OneToOneField(Screenplay, on_delete=models.CASCADE, primary_key=True)
    breakdown = models.URLField() 


    def generate_breakdown(self):
        with default_storage.open(self.screenplay.docfile.name, 'rb') as file:
            filename = self.screenplay.docfile.name
            target = filename.split('.pdf')[0] + '.xlsx'

            buffer = io.BytesIO()
            generated_file, self.screenplay.titre, self.screenplay.authors = handle_pdf.handling(file)

            generated_file.save(buffer)

            self.screenplay.save()

            self.breakdown = target
            content = ContentFile(buffer.getvalue())

            self.breakdown = default_storage.save(target, content)

            self.save()


@receiver(models.signals.post_delete, sender=Screenplay)
def auto_delete_screenplay_on_delete(sender, instance, **kwargs):
    """
    Deletes file from AWS S3 bucket
    when corresponding `Screenplay` object is deleted.
    """
    s3_client = boto3.client(
        's3',
        aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
        aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
        region_name='eu-north-1'
    )
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    
    if instance.docfile:
        object_key = f"{MEDIAFILES_LOCATION}/{instance.docfile}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )

@receiver(models.signals.post_delete, sender=Breakdown)
def auto_delete_breakdown_on_delete(sender, instance, **kwargs):
    """
    Deletes file from AWS S3 bucket
    when corresponding `Breakdown` object is deleted.
    """

    s3_client = boto3.client(
        's3',
        aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
        aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
        region_name='eu-north-1'
    )
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    
    if instance.breakdown:
        object_key = f"{MEDIAFILES_LOCATION}/{instance.breakdown}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )


@receiver(models.signals.pre_save, sender=Screenplay)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from AWS S3 bucket
    when corresponding `Screenplay` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        screenplay = Screenplay.objects.get(pk=instance.pk).docfile
    except Screenplay.DoesNotExist:
        return False

    new_file = instance.docfile
    if not screenplay == new_file:
        s3_client = boto3.client(
            's3',
            aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
            aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
            region_name='eu-north-1'
        )
        bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
        object_key = f"{MEDIAFILES_LOCATION}/{screenplay}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )

website/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

from .models import *

def file_size(value): 
    limit = 10 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('Veuillez limiter la taille du fichier à 10 Mo.')
    
class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='Choisissez un fichier',
        help_text='max. 10 Mo',
        validators=[file_size, FileExtensionValidator(['pdf'], "Le fichier attendu est au format pdf")]
    )


class ContactForm(forms.Form):
    Nom = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Votre nom", 'class': 'form-group'}), 
                          label="Nom")
    Email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Votre e-mail", 'class': 'form-group'}),
        error_messages={"invalid": "Veuillez renseigner une adresse email correcte"},
        label="Email"
    )
    Objet = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Objet", 'class': 'form-group'}), required=False, label="Objet")
    Message = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Votre message", 'class': 'form-group'}),
        label="Message"
    )

website/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import FileResponse, Http404
from django.core.files import File 
from google.oauth2 import id_token
from google.auth.transport import requests
from django.core.mail import send_mail
from django.utils import timezone
import os
import time
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth import get_user_model
from django.views.generic import TemplateView, FormView
from django.conf import settings
from .forms import UploadFileForm, ContactForm
from .models import Screenplay, Breakdown, Message
from website import send_email
from .tasks import process_breakdown
import sys


def breakdown_view(request):
    if request.method == "POST" and 'document_submit' in request.POST :
        form = UploadFileForm(request.POST, request.FILES)
        
        if form.is_valid():
            if not request.user.is_staff and len(Screenplay.objects.filter(user=request.user, created__month=timezone.now().month))>10:
                return HttpResponseRedirect("limites/")
            newdoc = Screenplay(docfile = request.FILES['file'], user=request.user)
            newdoc.save()
            breakdown = Breakdown(screenplay=newdoc)
            breakdown.save()
            process_breakdown.delay(newdoc.id)
            return redirect('/document-sent/') 
        else : 
            sys.stdout.write("form invalid")
    else:
        form = UploadFileForm()
        if request.session.get('has_seen_intro'):
            show_intro = False
        else : 
            request.session['has_seen_intro'] = True
            show_intro = True
    return render(
        request,
        'website/pages/home.html',
        {
            'form': form,
            'show_intro':show_intro,
        }
    )
    


class FormSuccessView(TemplateView):
    template_name = "website/pages/form-sent.html"
    
class DocumentSuccessView(TemplateView):
    template_name = "website/pages/document-sent.html"

def about_view(request):
    return render(request, "website/pages/about.html")

def productions_view(request):
    return render(request, "website/pages/productions.html")

def contact_view(request):
    if request.method == "POST":
        if 'contact_submit' in request.POST :
            contact_form = ContactForm(request.POST)
            form = UploadFileForm()
            if contact_form.is_valid():
                name = contact_form.cleaned_data['Nom']
                email = contact_form.cleaned_data['Email']
                subject = contact_form.cleaned_data['Objet']
                message = contact_form.cleaned_data['Message']

                full_message = f"""
                Received message below from {name} @ {email}, {subject}
                ________________________


                {message}
                """
                send_mail(
                    subject="Received contact form submission",
                    message=full_message,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[settings.NOTIFY_EMAIL],
                )
                message = Message(Nom = name, Email = email, Objet = subject, Message=message)
                message.save()

                return redirect('/form-sent/') 

    else:


        form = UploadFileForm()
        contact_form = ContactForm()
        if request.session.get('has_seen_intro'):
            show_intro = False
        else : 
            request.session['has_seen_intro'] = True
            show_intro = True
        return render(request, "website/pages/contact.html", {
            'contact_form': contact_form,
            'show_intro':show_intro,
        })

def limites(request):
    return render(request, "website/pages/limites.html")

def erreur(request):
    return render(request, "website/pages/erreur.html")

@login_required
def view_file(request):
    try : 
        f = open(request.path, 'rb')
        myfile = File(f)
        return FileResponse(myfile, content_type="application/pdf")
    except FileNotFoundError:
        raise Http404()
    
@csrf_exempt
def auth_receiver(request):
    token = request.POST.get('credential')
    retry = 0
    while retry < 5 :
        try:
            user_data = id_token.verify_oauth2_token(
                token, requests.Request(), os.environ['GOOGLE_OAUTH_CLIENT_ID']
            )
            break
        except ValueError:
            retry += 1
            if retry == 5:
                return HttpResponse(status=403)
        time.sleep(1)
    try : 
        email = user_data['email']
        User = get_user_model()
        user, created = User.objects.get_or_create(username=email, email=email)
        login(request, user)
        request.session['user_data'] = user_data
    except : 
        return redirect("erreur/")

    return redirect('/')                        

def sign_out(request):
    if 'user_data' in request.session:
        del request.session['user_data']
    logout(request)
    return redirect('/')

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr" data-fr-scheme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no">
    <meta name="theme-color" content="#000091">
    <title>DORYLUS PRODUCTIONS</title>
    <meta property="og:title" content="Dorylus" />
    <meta property="og:image" content="{% static 'website/images/Vignette.jpg' %}" />
    <meta property="og:description" content="Votre assistant de production." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.dorylus.eu" />
    <meta name="description" content="Société de production de films basée à Paris. Dorylus accompagne les auteurs et leur fournit les outils nécessaires au développement de leur projet.">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'website/css/website.css' %}">

    
    <link rel="icon" type="image/png" href="{% static 'website/favicon/favicon-96x96.png' %}" sizes="96x96"  />
    <link rel="icon" type="image/svg+xml" href="{% static 'website/favicon/favicon.svg' %}"/>
    <link rel="shortcut icon" href="{% static 'website/favicon/favicon.ico' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'website/favicon/apple-touch-icon.png' %}" />
    <meta name="apple-mobile-web-app-title" content="core" />
    <link rel="manifest" href="{% static 'website/favicon/site.webmanifest' %}" />
</head>
<body>

<header class="header">
    {% if not show_intro %}
    <div class="header-video">
        <img src="{% static 'website/images/banner_small.jpg' %}" type="image/jpeg" alt="Banner Dorylus Productions" class="header-video"/> 
    </div>
    {% else %}
    <video class="header-video" playsinline autoplay muted >
        <source src="{% static 'website/videos/video_banner_smaller.mp4' %}" type="video/mp4" /> Votre navigateur ne supporte pas la lecture de cette vidéo.
    </video>    

    {% endif %}

</header>
<main>
    <nav id="mainNav">
        <ul >
            <li class="nav-item"><a href="{% url 'website:about' %}">A propos</a></li>
            <li class="nav-item"><a href="{% url 'website:productions' %}">Réalisations</a></li>
            <li class="nav-item"><a href="{% url 'website:breakdown' %}">Assistant de production</a> </li>
            <li class="nav-item"><a href="{% url 'website:contact' %}">Contact</a></li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}

</main>

<footer>
    <div>&copy; 2025 Dorylus Productions.</div>
    <div><a href="https://www.instagram.com/dorylusproductions/" class="instagram-link" target="_blank" rel="noopener noreferrer">
        <img src="{% static 'website/images/Instagram_Glyph_White.svg' %}" alt="Instagram Logo" class="logo">
    </a></div>
</footer>


</body>
</html>