core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]



from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

website/urls.py
from django.urls import path, re_path


from .views import (
    breakdown_view,
    about_view,
    productions_view,
    contact_view,
    view_file,
    limites,
    auth_receiver,
    sign_out,
    erreur,
    FormSuccessView,
    DocumentSuccessView,
)

app_name = "website"

urlpatterns = [
    path("about/", about_view, name="about"),
    path("productions/", productions_view, name="productions"),
    path("", breakdown_view, name="breakdown"),
    path("contact/", contact_view, name="contact"),
    path('limites/', limites, name='limites'),
    re_path(r'media/documents/[0-9]{4}/[0-9]{2}/[0-9]{2}/.+', view_file, name="view-file"),
    path('sign-out/', sign_out, name='sign_out'),
    path('auth-receiver/', auth_receiver, name='auth_receiver'),
    path('erreur/', erreur, name='erreur'),
    path("form-sent/", FormSuccessView.as_view(), name="form-sent"),
    path('document-sent/', DocumentSuccessView.as_view(), name='document-success'),
]

website/models.py
import io
from django.db import models
from django.core.validators import FileExtensionValidator
from website import handle_pdf
from django.dispatch import receiver
import os
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
import boto3
from core.settings import MEDIAFILES_LOCATION

class Message(models.Model):
    Nom = models.CharField(max_length=254)
    Email = models.EmailField()
    Objet = models.CharField(max_length=254)
    Message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

class Screenplay(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d',  validators=[FileExtensionValidator(['pdf'])])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created = models.DateTimeField(auto_now_add=True)
    titre = models.CharField(max_length=254, default="")
    authors = models.CharField(max_length=254, default="")
    

class Breakdown(models.Model):
    screenplay = models.OneToOneField(Screenplay, on_delete=models.CASCADE, primary_key=True)
    breakdown = models.URLField() 


    def generate_breakdown(self):
        with default_storage.open(self.screenplay.docfile.name, 'rb') as file:
            filename = self.screenplay.docfile.name
            target = filename.split('.pdf')[0] + '.xlsx'

            buffer = io.BytesIO()
            generated_file, self.screenplay.titre, self.screenplay.authors = handle_pdf.handling(file)

            generated_file.save(buffer)

            self.screenplay.save()

            self.breakdown = target
            content = ContentFile(buffer.getvalue())

            self.breakdown = default_storage.save(target, content)

            self.save()


@receiver(models.signals.post_delete, sender=Screenplay)
def auto_delete_screenplay_on_delete(sender, instance, **kwargs):
    """
    Deletes file from AWS S3 bucket
    when corresponding `Screenplay` object is deleted.
    """
    s3_client = boto3.client(
        's3',
        aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
        aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
        region_name='eu-north-1'
    )
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    
    if instance.docfile:
        object_key = f"{MEDIAFILES_LOCATION}/{instance.docfile}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )

@receiver(models.signals.post_delete, sender=Breakdown)
def auto_delete_breakdown_on_delete(sender, instance, **kwargs):
    """
    Deletes file from AWS S3 bucket
    when corresponding `Breakdown` object is deleted.
    """

    s3_client = boto3.client(
        's3',
        aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
        aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
        region_name='eu-north-1'
    )
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    
    if instance.breakdown:
        object_key = f"{MEDIAFILES_LOCATION}/{instance.breakdown}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )


@receiver(models.signals.pre_save, sender=Screenplay)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from AWS S3 bucket
    when corresponding `Screenplay` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        screenplay = Screenplay.objects.get(pk=instance.pk).docfile
    except Screenplay.DoesNotExist:
        return False

    new_file = instance.docfile
    if not screenplay == new_file:
        s3_client = boto3.client(
            's3',
            aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
            aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
            region_name='eu-north-1'
        )
        bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
        object_key = f"{MEDIAFILES_LOCATION}/{screenplay}"
        response = s3_client.delete_object(
            Bucket=bucket_name,
            Key=object_key
        )

website/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

from .models import *

def file_size(value): 
    limit = 10 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('Veuillez limiter la taille du fichier à 10 Mo.')
    
class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='Choisissez un fichier',
        help_text='max. 10 Mo',
        validators=[file_size, FileExtensionValidator(['pdf'], "Le fichier attendu est au format pdf")]
    )


class ContactForm(forms.Form):
    Nom = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Votre nom", 'class': 'form-group'}), 
                          label="Nom")
    Email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Votre e-mail", 'class': 'form-group'}),
        error_messages={"invalid": "Veuillez renseigner une adresse email correcte"},
        label="Email"
    )
    Objet = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Objet", 'class': 'form-group'}), required=False, label="Objet")
    Message = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Votre message", 'class': 'form-group'}),
        label="Message"
    )

website/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import FileResponse, Http404
from django.core.files import File 
from google.oauth2 import id_token
from google.auth.transport import requests
from django.core.mail import send_mail
from django.utils import timezone
import os
import time
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth import get_user_model
from django.views.generic import TemplateView, FormView
from django.conf import settings
from .forms import UploadFileForm, ContactForm
from .models import Screenplay, Breakdown, Message
from website import send_email
from .tasks import process_breakdown
import sys


def breakdown_view(request):
    if request.method == "POST" and 'document_submit' in request.POST :
        form = UploadFileForm(request.POST, request.FILES)
        
        if form.is_valid():
            if not request.user.is_staff and len(Screenplay.objects.filter(user=request.user, created__month=timezone.now().month))>10:
                return HttpResponseRedirect("limites/")
            newdoc = Screenplay(docfile = request.FILES['file'], user=request.user)
            newdoc.save()
            breakdown = Breakdown(screenplay=newdoc)
            breakdown.save()
            process_breakdown.delay(newdoc.id)
            return redirect('/document-sent/') 
        else : 
            sys.stdout.write("form invalid")
    else:
        form = UploadFileForm()
        if request.session.get('has_seen_intro'):
            show_intro = False
        else : 
            request.session['has_seen_intro'] = True
            show_intro = True
    return render(
        request,
        'website/pages/home.html',
        {
            'form': form,
            'show_intro':show_intro,
        }
    )
    


class FormSuccessView(TemplateView):
    template_name = "website/pages/form-sent.html"
    
class DocumentSuccessView(TemplateView):
    template_name = "website/pages/document-sent.html"

def about_view(request):
    return render(request, "website/pages/about.html")

def productions_view(request):
    return render(request, "website/pages/productions.html")

def contact_view(request):
    if request.method == "POST":
        if 'contact_submit' in request.POST :
            contact_form = ContactForm(request.POST)
            form = UploadFileForm()
            if contact_form.is_valid():
                name = contact_form.cleaned_data['Nom']
                email = contact_form.cleaned_data['Email']
                subject = contact_form.cleaned_data['Objet']
                message = contact_form.cleaned_data['Message']

                full_message = f"""
                Received message below from {name} @ {email}, {subject}
                ________________________


                {message}
                """
                send_mail(
                    subject="Received contact form submission",
                    message=full_message,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[settings.NOTIFY_EMAIL],
                )
                message = Message(Nom = name, Email = email, Objet = subject, Message=message)
                message.save()

                return redirect('/form-sent/') 

    else:


        form = UploadFileForm()
        contact_form = ContactForm()
        if request.session.get('has_seen_intro'):
            show_intro = False
        else : 
            request.session['has_seen_intro'] = True
            show_intro = True
        return render(request, "website/pages/contact.html", {
            'contact_form': contact_form,
            'show_intro':show_intro,
        })

def limites(request):
    return render(request, "website/pages/limites.html")

def erreur(request):
    return render(request, "website/pages/erreur.html")

@login_required
def view_file(request):
    try : 
        f = open(request.path, 'rb')
        myfile = File(f)
        return FileResponse(myfile, content_type="application/pdf")
    except FileNotFoundError:
        raise Http404()
    
@csrf_exempt
def auth_receiver(request):
    token = request.POST.get('credential')
    retry = 0
    while retry < 5 :
        try:
            user_data = id_token.verify_oauth2_token(
                token, requests.Request(), os.environ['GOOGLE_OAUTH_CLIENT_ID']
            )
            break
        except ValueError:
            retry += 1
            if retry == 5:
                return HttpResponse(status=403)
        time.sleep(1)
    try : 
        email = user_data['email']
        User = get_user_model()
        user, created = User.objects.get_or_create(username=email, email=email)
        login(request, user)
        request.session['user_data'] = user_data
    except : 
        return redirect("erreur/")

    return redirect('/')                        

def sign_out(request):
    if 'user_data' in request.session:
        del request.session['user_data']
    logout(request)
    return redirect('/')

website/templates/website/pages/about.html
{% extends "website/base.html" %}

{% block content %}
{% load static %}
<section id="about">
    <div class="subsection" id="edito">
        <h2>A PROPOS</h2>
        <p>Dorylus est le nom scientifique d'un genre de fourmis légionnaires, également appelé <u id="producteur">Magnan</u>.</p>
        <p>Nous accueillons des projets de courts-métrages de fiction, documentaires et séries courtes </p>
        <div class="animated-text">
            <p>avec une vigilance particulière quant au fait qu'ils reposent sur un conflit - exprimé avec ou sans violence.</p>
            <p>Nous nous précipitons sur vos scénarios pour les <a href="{% url 'website:breakdown'%}">dépouiller en quelques minutes</a>, puis les décortiquer consciencieusement et faire apparaître leur squelette.</p>
            <p>Notre ligne éditoriale est issue d'une géométrie non-euclidienne : le plus court chemin n'est pas forcément la ligne droite.</p>
            <p>C'est un sentier de phéromones qu'on se plait à tracer instinctivement, </p>
            <p>n’hésitant pas à faire un détour lorsque nous détectons des qualités primaires, sensorielles, physiologiques </p>   
            <p>qui activent notre système lymphatique. </p>
            <p>Si les défis techniques titillent nos mandibules, notre abdomen ne peut en digérer qu’un à la fois. </p>  
            <p>Ainsi nous construisons patiemment une galerie souterraine de projets dont les porteurs ont tous quelque chose à communiquer à leur public, </p>
            <p>et pour cela préfèrent la danse ou l'antennation à la trophallaxie. </p>
        </div>
    </div>

</section>

<div id="sidebar" class="sidebar">
    <div class="sidebar-content">
        <img src="{% static 'website/images/pierre_magnan.jpg' %}" alt="Pierre Magnan" class="sidebar-image">
        <div class="sidebar-text">
            <p>Culturellement proche des industries techniques et des métiers d’ingénierie du fait de sa formation initiale, <b>Pierre Magnan</b> se forme à la production en quelques courtes années d'assistanat auprès de plusieurs sociétés. </p>
            <p>Il crée la société Dorylus Productions en 2024, afin de développer en fiction le précepte de Zweig :</p>
            <blockquote> <i>Plus un esprit se limite et plus il touche par ailleurs à l’infini.</i></blockquote>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const producteur = document.getElementById('producteur');
        const sidebar = document.getElementById('sidebar');
        const aboutSection = document.getElementById('about');

        function showSidebar() {
            event.stopPropagation(); 
            sidebar.style.opacity = '1'; 
        };
        
        function hideSidebar() {
            sidebar.style.opacity = '0';
        }

        producteur.addEventListener('mouseenter', showSidebar)
        producteur.addEventListener('mouseleave', hideSidebar)

        if (/Mobi|Android|Tablet|iPad/i.test(navigator.userAgent)) {
            producteur.addEventListener('click', function(event) {
                showSidebar()
            })
            document.addEventListener('click', function(event) {
                if (!sidebar.contains(event.target) && event.target !== producteur) {
                    hideSidebar();
                }
            });

            sidebar.addEventListener('click', function(event) {
                event.stopPropagation(); 
            });
        } 

        
    });

    document.addEventListener('DOMContentLoaded', function() {
        const lines = document.querySelectorAll('.animated-text p');
        let delay = 1000;

        lines.forEach((line, index) => {
            setTimeout(() => {
                line.classList.add('visible');
            }, delay);
            delay += 1000;
        });
    });
</script>
{% endblock %}

website/templates/website/pages/contact.html
{% extends "website/base.html" %}


{% block content %}

<section>
<div id="contact" class="subsection">
    <h2>CONTACT</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <p>{{ contact_form.Nom }}</p>
            
            <p>{{ contact_form.Email.errors.0 }}
                {{ contact_form.Email }}
            </p>
            <p>{{ contact_form.Objet }}</p>
            <p>{{ contact_form.Message }}</p>

        </div>
        
        <div class="form-group">
            <button type="submit" name="contact_submit">Envoyer le message</button>
        </div>
    </form>
</div>
</section>



{% endblock %}

website/templates/website/pages/document-sent.html
{% extends "website/base.html" %}

{% block content %}

<section>
    <div class="subsection">
        <h2>Merci !</h2>
        <p>Vous recevrez votre dépouillement par email d'ici quelques minutes</p>
        <p>Pensez à vérifier dans vos spams si ce n'est pas le cas 😀</p>
    </div>
</section>

{% endblock %}

website/templates/website/pages/erreur.html
{% extends "website/base.html" %}

{% block content %}
<section>
    <h2>Désolé !</h2>
    <p>Il semble y avoir eu une erreur avec votre authentification</p>
    <p>Cette erreur est en cours de résolution, merci de votre patience.</p>
</section>

{% endblock %}

website/templates/website/pages/form-sent.html
{% extends "website/base.html" %}

{% block content %}
<section>
    <h2>Merci d'avoir pris contact avec Dorylus Productions.</h2>
    <p>Nous reviendrons vers vous dès que possible.</p>
</section>

{% endblock %}

website/templates/website/pages/home.html
{% extends "website/base.html" %}


{% block content %}

<section>
    <div class="subsection">
        <h2>PRÉPARONS VOTRE TOURNAGE</h2>
        
        {% if request.session.user_data %}
        <div>
        <p>Chargez votre scénario au format pdf</p>
        <p>Votre dépouillement sera envoyé à l'adresse {{ request.session.user_data.email }}
        <a href="{% url 'website:sign_out' %}"> Déconnexion </a> </p>

        <p>{% include "website/components/upload.html" %}</p>

        </div>
        {% else %}
        <div>
            <p>Recevez en quelques minutes le dépouillement général de votre film au format Excel, complété par IA séquence par séquence.</p>
            <p>Connexion requise - envoi par email.</p>
            <script src="https://accounts.google.com/gsi/client" async></script>
            <div id="g_id_onload"
                data-client_id="696523004881-etfuost1ghkqo9283euo8gep5ttgkrs2.apps.googleusercontent.com"
                data-context="signin"
                data-ux_mode="popup"
                data-login_uri="{% url 'website:auth_receiver' %}"
                data-auto_prompt="false">
            </div>
            <div class="center-container">
                <div class="g_id_signin"
                    data-type="standard"
                    data-shape="rectangular"
                    data-theme="outline"
                    data-text="signin_with"
                    data-size="large"
                    data-logo_alignment="left">
                </div>
            </div>
        </div>
        {% endif %}
        <p>{% include "website/components/faq.html" %}</p>
    </div>
</section>
{% endblock %}

website/templates/website/pages/limites.html

{% extends "website/base.html" %}

{% block content %}
<section>
    <h2>Désolé !</h2>
    <p>Nous limitons ce service gratuit à 10 utilisations par visiteur et par mois</p>
    <p>N'hésitez pas à nous <a href="{%url 'website:contact' %}">contacter</a> si vous souhaitez l'utiliser davantage.</p>
</section>

{% endblock %}

website/templates/website/pages/productions.html
{% extends "website/base.html" %}

{% load static %}
{% block content %}

<section id="films">
    <div class="gallery">
        <div class="gallery-item">
            <div class="blur-load" style="background-image: url('{% static 'website/images/ffw2_small.jpg' %}')">
                <img src="{% static 'website/images/ffw2.png' %}" loading="lazy" alt="Fast Forward" class="gallery-img">
            </div>
            <div class="overlay">
                <div class="title"><h3>FAST FORWARD</h3></div>
                <div class="overlayhover">
                    <p>Fiction - court-métrage - 2024 - réal. Quentin Muteau - avec Paul Lapierre, Oscar Tresanini - en diffusion <img src="{% static 'website/images/artefact_logo.png' %}" alt="Artefact Logo" class="logo"></p>
                    <p><u>Synopsis :</u> Laurent décide de renoncer à son SUV et de se remettre au vélo. Il s’élance sur la route avec son fils Axel installé dans une remorque, et tous deux entreprennent de remettre au goût du jour l’antiquité avec laquelle ils roulent. Une course à la modernisation est lancée, saura-t-on l'arrêter à temps ?</p>
                    <p><a href="{% static 'website/documents/FAST_FORWARD_memoire_technique&artistique_SD.pdf' %}" target="_blank">Téléchargez le dossier du film</a></p>
                </div>
            </div>  
        </div>
        <div class="gallery-item">
            <div class="blur-load" style="background-image: url('{% static 'website/images/detonations_small.jpg' %}')">
                <img src="{% static 'website/images/detonations.png' %}" loading="lazy" alt="Détonations" class="gallery-img">
            </div>
            <div class="overlay">
                <div class="title"><h3>DÉTONATIONS</h3></div>
                <div class="overlayhover">
                    <p>Documentaire - 2025 - réal. Pierre Magnan - en production</p>
                    <p><u>Synopsis :</u> Un après-midi de juillet, sur le champ de tir d'un feu d'artifice. Le montage se fait dans le calme, l'ambiance est appliquée, ça transpire. "Fais gaffe où tu mets les pieds", nous dit un artificier alors que nous traversons une série de <i>lignes</i> de fil électrique posées au sol. Soudain résonnent des bruits incongrus : est-ce un crachat ? un éternuement ? une exclamation ? des cris de douleur ?</i></p>
                    <p><i>Détonations </i> est une plongée démystifiante dans la réalité des <i>phobies d'impulsion</i>, entre animation et prise de vues réelles</p>
                </div>
            </div>  
        </div>
        <div class="gallery-item">
            <div class="blur-load" style="background-image: url('{% static 'website/images/lemariage_3_small.jpg' %}')">
                <img src="{% static 'website/images/lemariage_3.png' %}" loading="lazy" alt="Le Mariage" class="gallery-img">
            </div>
            <div class="overlay">
                <div class="title"><h3>LE MARIAGE</h3></div>
                <div class="overlayhover">
                    <p>Fiction audio - 2024 - réal. Clélia Sarotte - en diffusion <a href="https://www.carbone4.com/" target="_blank"><img src="{% static 'website/images/carbone4.png' %}" alt="Carbone4 Logo" class="logo"></a></p>
                    <p><u>Synopsis :</u>En 2060, Julia vient d'ouvrir son agence de mariage et sa première cliente souhaite organiser un <i>destination wedding</i>. Alors que chaque épisode incrémente d'un degré l'amplitude du réchauffement planétaire, Julia va devoir redoubler d'inventivité pour adapter l'organisation de ce mariage à de nouveaux enjeux climatiques et sécuritaires.</p>
                </div>
            </div>  
        </div>
        <div class="gallery-item">
            <div class="blur-load" style="background-image: url('{% static 'website/images/SansUnMot_STILL_crop_small.jpg' %}')">
                <img src="{% static 'website/images/SansUnMot_STILL_crop.jpg' %}" loading="lazy" alt="Sans un mot" class="gallery-img">
            </div>
            <div class="overlay">
                <div class="title"><h3>SANS UN MOT</h3></div>
                <div class="overlayhover">
                    <p>Fiction - court-métrage - 2023 - réal. Alexandre Gneouchev - en diffusion <a href="https://www.femis.fr/" target="_blank"><img src="{% static 'website/images/la-femis-logo.png' %}" alt="La Fémis Logo" class="logo"></a></p>
                    <p><u>Synopsis :</u>Qu’est-ce qu’il se passe si je n’y vais pas ? Si je ne fais rien ? Si je me laisse dériver... C’est ce que va faire le personnage principal du film, qui par la défection et le rejet va embrasser une déchéance sociale rapide dans un monde où le langage se déstructure et disparaît autour de lui.</p>
                </div>
            </div>  
        </div>


</section>
<script>
    const blurDivs = document.querySelectorAll(".blur-load")
    blurDivs.forEach(div => {
        const img = div.querySelector("img")

        function loaded() {
            div.classList.add("loaded")
        }
        if (img.complete) {
            loaded()
        } else {
            img.addEventListener("load", loaded)
        }
    }

    )
</script>
{% endblock %}